-- MySQL Script generated by MySQL Workbench
-- Tue Mar  3 22:01:30 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema universidad
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `universidad` ;

-- -----------------------------------------------------
-- Schema universidad
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `universidad` DEFAULT CHARACTER SET utf8 ;
USE `universidad` ;

-- -----------------------------------------------------
-- Table `universidad`.`carrera`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `universidad`.`carrera` ;

CREATE TABLE IF NOT EXISTS `universidad`.`carrera` (
  `codigo` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `titulo` VARCHAR(45) NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `universidad`.`cursos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `universidad`.`curso` ;

CREATE TABLE IF NOT EXISTS `universidad`.`curso` (
  `codigo` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `creditos` INT NULL,
  `horas` INT NULL,
  `carrera_codigo` VARCHAR(20) NOT NULL,
  `ciclo` INT NULL,
  `anio` INT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_cursos_carrera_idx` (`carrera_codigo` ASC) VISIBLE,
  CONSTRAINT `fk_cursos_carrera`
    FOREIGN KEY (`carrera_codigo`)
    REFERENCES `universidad`.`carrera` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `universidad`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `universidad`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `universidad`.`usuarios` (
  `cedula` VARCHAR(10) NOT NULL,
  `nombre` VARCHAR(20) NULL,
  `apellido1` VARCHAR(20) NULL,
  `apellido2` VARCHAR(20) NULL,
  `contrasenia` VARCHAR(45) NULL,
  PRIMARY KEY (`cedula`))
ENGINE = InnoDB;



insert into usuarios (cedula,nombre,apellido1,apellido2,contrasenia) values ('admin','admin','admin1','admin2','admin');
insert into usuarios (cedula,nombre,apellido1,apellido2,contrasenia) values ('116810263','Diego','Monterrey','Benavides','666');
insert into usuarios (cedula,nombre,apellido1,apellido2,contrasenia) values ('504210953','Djenane','Hernandez','Rodriguez','777');
commit;

insert into carrera (codigo,nombre,titulo) values ('EIF123','Informatica','Bachillerato');
insert into carrera (codigo,nombre,titulo) values ('LIX456','Ingles','Licenciatura');
insert into carrera (codigo,nombre,titulo) values ('TOP789','Topografia','Mestria');
insert into carrera (codigo,nombre,titulo) values ('GAS369','Gastronomia','Bachillerato');
insert into carrera (codigo,nombre,titulo) values ('MED741','Medicina','Maestria');
commit;

insert into curso (codigo,nombre,creditos,horas,carrera_codigo,ciclo,anio) values ('INF123','Progra 4',4,8,'EIF123',1,2020);
insert into curso (codigo,nombre,creditos,horas,carrera_codigo,ciclo,anio) values ('ING456','Conversacion 2',3,5,'LIX456',2,2022);
insert into curso (codigo,nombre,creditos,horas,carrera_codigo,ciclo,anio) values ('TGP789','Suelo 2',4,6,'TOP789',3,2020);
insert into curso (codigo,nombre,creditos,horas,carrera_codigo,ciclo,anio) values ('COD369','Postres 3',2,4,'GAS369',1,2023);
insert into curso (codigo,nombre,creditos,horas,carrera_codigo,ciclo,anio) values ('CIR741','Cirugia 5',6,12,'MED741',2,2021);
commit;






SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
SET GLOBAL time_zone = '-6:00';
